language: java

jdk:
  - openjdk8

script:
  - ./gradlew check
  - ./gradlew -p sample check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

notifications:
  email: true

